In [1]:
import pandas as pd
for i in range(8,23):
    globals()[f'w_{i}'] = pd.read_csv(f'C:/workspace/data/기상정보/기상정보_{i}.csv', encoding='CP949')
w_8

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,108,서울,2008-01-01 00:00,-7.0,0,NaN,NaN,3.5,0,270,...,10.0,1500.0,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
1,108,서울,2008-01-01 01:00,-7.3,0,NaN,NaN,4.9,0,290,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
2,108,서울,2008-01-01 02:00,-7.5,0,NaN,NaN,4.1,0,270,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
3,108,서울,2008-01-01 03:00,-7.8,0,NaN,NaN,3.9,0,270,...,10.0,1500.0,4.0,NaN,-7.3,0,-4.0,-0.5,1.9,2.1
4,108,서울,2008-01-01 04:00,-7.9,0,NaN,NaN,4.0,0,290,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,108,서울,2008-12-31 19:00,-4.1,0,NaN,NaN,3.8,0,290,...,NaN,NaN,NaN,NaN,-6.5,0,NaN,NaN,NaN,NaN
8780,108,서울,2008-12-31 20:00,-5.3,0,NaN,NaN,5.4,0,290,...,NaN,NaN,NaN,NaN,-7.2,0,NaN,NaN,NaN,NaN
8781,108,서울,2008-12-31 21:00,-6.2,0,NaN,NaN,4.3,0,320,...,NaN,1600.0,4.0,NaN,-8.2,0,-2.2,-1.3,0.2,1.2
8782,108,서울,2008-12-31 22:00,-6.9,0,NaN,NaN,3.5,0,340,...,NaN,NaN,NaN,NaN,-8.9,0,NaN,NaN,NaN,NaN
8783,108,서울,2008-12-31 23:00,-7.3,0,NaN,NaN,1.7,0,320,...,NaN,NaN,NaN,NaN,-9.7,0,NaN,NaN,NaN,NaN

In [2]:
w_8.columns

Index(['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '강수량(mm)', '강수량 QC플래그',
       '풍속(m/s)', '풍속 QC플래그', '풍향(16방위)', '풍향 QC플래그', '습도(%)', '습도 QC플래그',
       '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)', '현지기압 QC플래그', '해면기압(hPa)',
       '해면기압 QC플래그', '일조(hr)', '일조 QC플래그', '일사(MJ/m2)', '일사 QC플래그', '적설(cm)',
       '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)', '운형(운형약어)', '최저운고(100m )',
       '시정(10m)', '지면상태(지면상태코드)', '현상번호(국내식)', '지면온도(°C)', '지면온도 QC플래그',
       '5cm 지중온도(°C)', '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)'],
      dtype='object')

In [3]:
w_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   지점             8784 non-null   int64
 1   지점명            8784 non-null   object
 2   일시             8784 non-null   object
 3   기온(°C)         8784 non-null   float64
 4   기온 QC플래그       8784 non-null   int64
 5   강수량(mm)        805 non-null    float64
 6   강수량 QC플래그      2129 non-null   float64
 7   풍속(m/s)        8784 non-null   float64
 8   풍속 QC플래그       8784 non-null   int64
 9   풍향(16방위)       8784 non-null   int64
 10  풍향 QC플래그       8784 non-null   int64
 11  습도(%)          8784 non-null   int64
 12  습도 QC플래그       8784 non-null   int64
 13  증기압(hPa)       6950 non-null   float64
 14  이슬점온도(°C)      6950 non-null   float64
 15  현지기압(hPa)      6940 non-null   float64
 16  현지기압 QC플래그     8784 non-null   int64
 17  해면기압(hPa)      6940 non-null   float64
 18  해면기압 QC플래그     8784 non-null   int64
 19  일조(hr)         4803 non-null   float64
 20  일조 QC플래그       8784 non-null   int64
 21  일사(MJ/m2)      4801 non-null   float64
 22  일사 QC플래그       8784 non-null   int64
 23  적설(cm)         228 non-null    float64
 24  3시간신적설(cm)     29 non-null     float64
 25  전운량(10분위)      6819 non-null   float64
 26  중하층운량(10분위)    6420 non-null   float64
 27  운형(운형약어)       4445 non-null   object
 28  최저운고(100m )    4719 non-null   float64
 29  시정(10m)        6817 non-null   float64
 30  지면상태(지면상태코드)   1466 non-null   float64
 31  현상번호(국내식)      3564 non-null   float64
 32  지면온도(°C)       6456 non-null   float64
 33  지면온도 QC플래그     8784 non-null   int64
 34  5cm 지중온도(°C)   1464 non-null   float64
 35  10cm 지중온도(°C)  1464 non-null   float64
 36  20cm 지중온도(°C)  1464 non-null   float64
 37  30cm 지중온도(°C)  1464 non-null   float64
dtypes: float64(23), int64(12), object(3)
memory usage: 2.5+ MB

In [4]:
weathers = []
for i in range(8,23):
    weathers.append(globals()[f'w_{i}'])
weathers

[       지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2008-01-01 00:00    -7.0         0      NaN        NaN
 1     108  서울  2008-01-01 01:00    -7.3         0      NaN        NaN
 2     108  서울  2008-01-01 02:00    -7.5         0      NaN        NaN
 3     108  서울  2008-01-01 03:00    -7.8         0      NaN        NaN
 4     108  서울  2008-01-01 04:00    -7.9         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8779  108  서울  2008-12-31 19:00    -4.1         0      NaN        NaN
 8780  108  서울  2008-12-31 20:00    -5.3         0      NaN        NaN
 8781  108  서울  2008-12-31 21:00    -6.2         0      NaN        NaN
 8782  108  서울  2008-12-31 22:00    -6.9         0      NaN        NaN
 8783  108  서울  2008-12-31 23:00    -7.3         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         3.5         0       270  ...         10.0   1500.0           NaN
 1         4.9         0       290  ...          NaN      NaN           NaN
 2         4.1         0       270  ...          NaN      NaN           NaN
 3         3.9         0       270  ...         10.0   1500.0           4.0
 4         4.0         0       290  ...          NaN      NaN           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8779      3.8         0       290  ...          NaN      NaN           NaN
 8780      5.4         0       290  ...          NaN      NaN           NaN
 8781      4.3         0       320  ...          NaN   1600.0           4.0
 8782      3.5         0       340  ...          NaN      NaN           NaN
 8783      1.7         0       320  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0           NaN       NaN           9           NaN            NaN
 1           NaN       NaN           9           NaN            NaN
 2           NaN       NaN           9           NaN            NaN
 3           NaN      -7.3           0          -4.0           -0.5
 4           NaN       NaN           9           NaN            NaN
 ...         ...       ...         ...           ...            ...
 8779        NaN      -6.5           0           NaN            NaN
 8780        NaN      -7.2           0           NaN            NaN
 8781        NaN      -8.2           0          -2.2           -1.3
 8782        NaN      -8.9           0           NaN            NaN
 8783        NaN      -9.7           0           NaN            NaN

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0               NaN            NaN
 1               NaN            NaN
 2               NaN            NaN
 3               1.9            2.1
 4               NaN            NaN
 ...             ...            ...
 8779            NaN            NaN
 8780            NaN            NaN
 8781            0.2            1.2
 8782            NaN            NaN
 8783            NaN            NaN

 [8784 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2009-01-01 00:00    -7.6         0      NaN        NaN
 1     108  서울  2009-01-01 01:00    -7.8         0      NaN        NaN
 2     108  서울  2009-01-01 02:00    -8.1         0      NaN        NaN
 3     108  서울  2009-01-01 03:00    -8.5         0      NaN        NaN
 4     108  서울  2009-01-01 04:00    -8.8         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8755  108  서울  2009-12-31 19:00   -10.3         0      NaN        NaN
 8756  108  서울  2009-12-31 20:00   -10.7         0      NaN        NaN
 8757  108  서울  2009-12-31 21:00   -11.1         0      NaN        NaN
 8758  108  서울  2009-12-31 22:00   -11.6         0      NaN        NaN
 8759  108  서울  2009-12-31 23:00   -11.7         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         2.1         0       290  ...          NaN   1600.0           NaN
 1         2.3         0       320  ...          NaN      NaN           NaN
 2         2.0         0       340  ...          NaN      NaN           NaN
 3         2.4         0       290  ...          NaN   1500.0           4.0
 4         2.1         0       320  ...          NaN   1500.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8755      4.1         0       290  ...          NaN      NaN           NaN
 8756      1.9         0       290  ...          NaN      NaN           NaN
 8757      2.1         0       320  ...          NaN   2000.0          16.0
 8758      2.5         0       290  ...          NaN      NaN           NaN
 8759      2.2         0       290  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0           NaN     -10.1           0           NaN            NaN
 1           NaN     -10.3           0           NaN            NaN
 2           NaN     -10.8           0           NaN            NaN
 3           NaN     -10.7           0          -4.0           -2.3
 4           NaN     -11.0           0           NaN            NaN
 ...         ...       ...         ...           ...            ...
 8755        NaN      -4.9           0          -3.5           -1.3
 8756        NaN      -5.3           0          -3.8           -1.5
 8757        NaN      -5.6           0          -4.1           -1.7
 8758        NaN      -6.0           0          -4.3           -1.8
 8759        NaN      -6.2           0          -4.5           -1.9

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0               NaN            NaN
 1               NaN            NaN
 2               NaN            NaN
 3               0.0            1.2
 4               NaN            NaN
 ...             ...            ...
 8755           -0.3            0.7
 8756           -0.3            0.7
 8757           -0.4            0.6
 8758           -0.4            0.7
 8759           -0.5            0.6

 [8760 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2010-01-01 00:00   -11.5         0      NaN        NaN
 1     108  서울  2010-01-01 01:00   -11.0         0      NaN        NaN
 2     108  서울  2010-01-01 02:00   -11.1         0      NaN        NaN
 3     108  서울  2010-01-01 03:00   -12.1         0      NaN        NaN
 4     108  서울  2010-01-01 04:00   -12.3         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8755  108  서울  2010-12-31 19:00    -8.0         0      NaN        NaN
 8756  108  서울  2010-12-31 20:00    -8.6         0      NaN        NaN
 8757  108  서울  2010-12-31 21:00    -9.1         0      NaN        NaN
 8758  108  서울  2010-12-31 22:00    -9.5         0      NaN        NaN
 8759  108  서울  2010-12-31 23:00    -9.7         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         3.1         0       340  ...          NaN   2000.0           NaN
 1         1.2         0       290  ...          NaN      NaN           NaN
 2         1.7         0        20  ...          NaN      NaN           NaN
 3         1.6         0        20  ...          NaN   2000.0          16.0
 4         1.4         0        20  ...          NaN   2000.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8755      3.2         0       290  ...          NaN      NaN           NaN
 8756      3.2         0       340  ...          NaN      NaN           NaN
 8757      1.7         0       360  ...          NaN   1800.0          13.0
 8758      1.7         0       360  ...          NaN      NaN           NaN
 8759      0.9         0       270  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0           NaN      -6.4           0          -4.6           -2.0
 1           NaN      -6.5           0          -4.7           -2.1
 2           NaN      -6.5           0          -4.8           -2.1
 3           NaN      -6.7           0          -4.9           -2.2
 4           NaN      -6.8           0          -5.0           -2.3
 ...         ...       ...         ...           ...            ...
 8755        NaN      -2.9           0          -1.6           -1.1
 8756        NaN      -3.2           0          -1.9           -1.2
 8757        NaN      -3.4           0          -2.1           -1.4
 8758        NaN      -3.7           0          -2.2           -1.5
 8759        NaN      -3.9           0          -2.4           -1.6

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0              -0.5            0.6
 1              -0.6            0.6
 2              -0.6            0.6
 3              -0.7            0.6
 4              -0.7            0.6
 ...             ...            ...
 8755           -0.9            0.0
 8756           -0.9            0.0
 8757           -1.0            0.0
 8758           -1.1            0.0
 8759           -1.1            0.0

 [8760 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2011-01-01 00:00    -9.8         0      NaN        NaN
 1     108  서울  2011-01-01 01:00    -9.9         0      NaN        NaN
 2     108  서울  2011-01-01 02:00   -10.2         0      NaN        NaN
 3     108  서울  2011-01-01 03:00   -10.1         0      NaN        NaN
 4     108  서울  2011-01-01 04:00   -10.0         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8755  108  서울  2011-12-31 19:00    -0.1         0      NaN        NaN
 8756  108  서울  2011-12-31 20:00    -0.1         0      NaN        NaN
 8757  108  서울  2011-12-31 21:00    -0.1         0      NaN        NaN
 8758  108  서울  2011-12-31 22:00     0.2         0      NaN        NaN
 8759  108  서울  2011-12-31 23:00     0.3         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         1.5         0     270.0  ...          NaN   1800.0           NaN
 1         0.5         0     360.0  ...          NaN      NaN           NaN
 2         2.3         0     270.0  ...          NaN      NaN           NaN
 3         2.6         0     270.0  ...          NaN   1800.0          13.0
 4         2.7         0     270.0  ...          NaN   1500.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8755      2.6         0     290.0  ...          NaN      NaN           NaN
 8756      2.0         0     290.0  ...          NaN      NaN           NaN
 8757      1.5         0     270.0  ...         10.0    600.0           4.0
 8758      1.9         0     230.0  ...          NaN      NaN           NaN
 8759      1.3         0     270.0  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0           NaN      -4.3           0          -2.6           -1.7
 1           NaN      -4.6           0          -2.8           -1.9
 2           NaN      -4.9           0          -3.0           -2.0
 3           NaN      -4.9           0          -3.1           -2.1
 4           NaN      -4.8           0          -3.1           -2.2
 ...         ...       ...         ...           ...            ...
 8755       40.0      -0.4           0          -0.3           -0.4
 8756       40.0      -0.4           0          -0.3           -0.4
 8757       40.0      -0.5           0          -0.3           -0.4
 8758       40.0      -0.7           0          -0.4           -0.4
 8759       40.0      -0.5           0          -0.3           -0.4

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0              -1.2            0.0
 1              -1.3            0.0
 2              -1.3            0.0
 3              -1.4            0.0
 4              -1.5           -0.1
 ...             ...            ...
 8755           -0.4            0.1
 8756           -0.4            0.1
 8757           -0.4            0.1
 8758           -0.4            0.1
 8759           -0.3            0.1

 [8760 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2012-01-01 00:00     0.4         0      NaN        NaN
 1     108  서울  2012-01-01 01:00     0.3         0      NaN        NaN
 2     108  서울  2012-01-01 02:00    -0.1         0      NaN        NaN
 3     108  서울  2012-01-01 03:00    -0.5         0      NaN        NaN
 4     108  서울  2012-01-01 04:00    -1.2         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8778  108  서울  2012-12-31 19:00    -8.0         0      NaN        NaN
 8779  108  서울  2012-12-31 20:00    -8.2         0      NaN        NaN
 8780  108  서울  2012-12-31 21:00    -7.9         0      NaN        NaN
 8781  108  서울  2012-12-31 22:00    -7.8         0      NaN        NaN
 8782  108  서울  2012-12-31 23:00    -8.0         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         1.5         0       250  ...         10.0    600.0           NaN
 1         2.3         0       270  ...          NaN      NaN           NaN
 2         1.3         0       290  ...          NaN      NaN           NaN
 3         0.8         0       270  ...         10.0    400.0           4.0
 4         1.5         0       290  ...         10.0    400.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8778      0.9         0       360  ...          NaN      NaN           NaN
 8779      1.3         0       270  ...          NaN      NaN           NaN
 8780      0.9         0       270  ...         10.0   2000.0          13.0
 8781      1.1         0        20  ...          NaN      NaN           NaN
 8782      3.1         0        50  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0          40.0      -0.6           0          -0.3           -0.4
 1          40.0      -0.6           0          -0.3           -0.3
 2          40.0      -1.2           0          -0.3           -0.3
 3          40.0      -1.7           0          -0.5           -0.4
 4          40.0      -2.7           0          -0.7           -0.4
 ...         ...       ...         ...           ...            ...
 8778        NaN      -2.6           0          -2.3           -1.1
 8779        NaN      -2.9           0          -2.6           -1.3
 8780        NaN      -3.1           0          -2.8           -1.3
 8781        NaN      -3.2           0          -2.9           -1.5
 8782        NaN      -3.2           0          -2.9           -1.5

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0              -0.3            0.1
 1              -0.3            0.1
 2              -0.3            0.2
 3              -0.3            0.1
 4              -0.3            0.2
 ...             ...            ...
 8778           -0.3            0.4
 8779           -0.4            0.3
 8780           -0.4            0.4
 8781           -0.4            0.3
 8782           -0.4            0.4

 [8783 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2013-01-01 00:00    -8.3         0      NaN        NaN
 1     108  서울  2013-01-01 01:00    -8.5         0      NaN        NaN
 2     108  서울  2013-01-01 02:00    -8.4         0      NaN        NaN
 3     108  서울  2013-01-01 03:00    -8.1         0      NaN        NaN
 4     108  서울  2013-01-01 04:00    -8.2         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8755  108  서울  2013-12-31 19:00     5.5         0      NaN        NaN
 8756  108  서울  2013-12-31 20:00     5.2         0      NaN        NaN
 8757  108  서울  2013-12-31 21:00     4.9         0      NaN        NaN
 8758  108  서울  2013-12-31 22:00     4.2         0      NaN        NaN
 8759  108  서울  2013-12-31 23:00     3.7         0      NaN        NaN

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         3.6         0        50  ...         10.0   2000.0           NaN
 1         4.0         0        50  ...          NaN      NaN           NaN
 2         4.0         0        70  ...          NaN      NaN           NaN
 3         3.4         0        70  ...         35.0   2000.0          13.0
 4         3.8         0        70  ...         35.0   2000.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8755      3.6         0       230  ...          NaN      NaN           NaN
 8756      2.7         0       250  ...          NaN      NaN           NaN
 8757      3.9         0       270  ...         10.0    600.0           1.0
 8758      3.6         0       270  ...          NaN      NaN           NaN
 8759      3.2         0       250  ...          NaN      NaN           NaN

       현상번호(국내식)  지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  \
 0           NaN      -3.3           0          -2.9           -1.6
 1           NaN      -3.4           0          -2.9           -1.6
 2           NaN      -3.4           0          -3.0           -1.6
 3           NaN      -3.4           0          -3.0           -1.6
 4           NaN      -3.4           0          -2.9           -1.7
 ...         ...       ...         ...           ...            ...
 8755       40.0       0.1           0           0.2           -0.2
 8756       40.0       0.1           0           0.2           -0.2
 8757       40.0       0.1           0           0.2           -0.2
 8758       40.0       0.1           0           0.2           -0.2
 8759       40.0       0.1           0           0.2           -0.2

       20cm 지중온도(°C)  30cm 지중온도(°C)
 0              -0.5            0.3
 1              -0.5            0.3
 2              -0.5            0.4
 3              -0.5            0.3
 4              -0.5            0.3
 ...             ...            ...
 8755            0.0            1.5
 8756            0.0            1.5
 8757            0.0            1.5
 8758            0.0            1.5
 8759            0.1            1.5

 [8760 rows x 38 columns],
        지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  \
 0     108  서울  2014-01-01 00:00     3.3         0      NaN        NaN
 1     108  서울  2014-01-01 01:00     2.6         0      NaN        NaN
 2     108  서울  2014-01-01 02:00     1.7         0      NaN        NaN
 3     108  서울  2014-01-01 03:00     1.4         0      NaN        NaN
 4     108  서울  2014-01-01 04:00     0.9         0      NaN        NaN
 ...   ...  ..               ...     ...       ...      ...        ...
 8755  108  서울  2014-12-31 19:00    -3.4         0      NaN        9.0
 8756  108  서울  2014-12-31 20:00    -4.4         0      NaN        9.0
 8757  108  서울  2014-12-31 21:00    -4.9         0      NaN        9.0
 8758  108  서울  2014-12-31 22:00    -5.4         0      NaN        9.0
 8759  108  서울  2014-12-31 23:00    -6.2         0      NaN        9.0

       풍속(m/s)  풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  \
 0         3.8         0     250.0  ...         10.0    600.0           NaN
 1         2.3         0     250.0  ...          NaN      NaN           NaN
 2         1.7         0     250.0  ...          NaN      NaN           NaN
 3         1.4         0     250.0  ...          NaN    600.0           4.0
 4         2.8         0     270.0  ...          NaN    600.0           NaN
 ...       ...       ...       ...  ...          ...      ...           ...
 8755      7.1         0     290.0  ...          NaN      NaN           NaN
 8756      5.6         0     290.0  ...          NaN      NaN           NaN
 8757      4.0         0     290.0  ...          NaN   2000.0           4.0

In [5]:
weather = pd.concat(weathers)
weather

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,108,서울,2008-01-01 00:00,-7.0,0.0,NaN,NaN,3.5,0.0,270.0,...,10.0,1500.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
1,108,서울,2008-01-01 01:00,-7.3,0.0,NaN,NaN,4.9,0.0,290.0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
2,108,서울,2008-01-01 02:00,-7.5,0.0,NaN,NaN,4.1,0.0,270.0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
3,108,서울,2008-01-01 03:00,-7.8,0.0,NaN,NaN,3.9,0.0,270.0,...,10.0,1500.0,4.0,NaN,-7.3,0.0,-4.0,-0.5,1.9,2.1
4,108,서울,2008-01-01 04:00,-7.9,0.0,NaN,NaN,4.0,0.0,290.0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,108,서울,2022-12-31 19:00,-0.2,NaN,NaN,9.0,1.8,NaN,20.0,...,NaN,1211.0,NaN,NaN,-0.9,NaN,-0.1,-0.5,-0.5,0.6
8756,108,서울,2022-12-31 20:00,-0.8,NaN,NaN,9.0,1.4,NaN,20.0,...,14.0,1171.0,NaN,NaN,-1.8,NaN,-0.1,-0.5,-0.5,0.6
8757,108,서울,2022-12-31 21:00,-1.0,NaN,NaN,9.0,0.9,NaN,340.0,...,13.0,1134.0,NaN,NaN,-2.8,NaN,-0.2,-0.5,-0.5,0.6
8758,108,서울,2022-12-31 22:00,-0.8,NaN,NaN,9.0,0.5,NaN,290.0,...,13.0,1094.0,NaN,NaN,-2.2,NaN,-0.3,-0.5,-0.5,0.6
8759,108,서울,2022-12-31 23:00,-0.2,NaN,NaN,9.0,1.3,NaN,230.0,...,14.0,1314.0,NaN,NaN,-2.1,NaN,-0.3,-0.5,-0.5,0.6

In [6]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131496 entries, 0 to 8759
Data columns (total 38 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   지점             131496 non-null  int64
 1   지점명            131496 non-null  object
 2   일시             131496 non-null  object
 3   기온(°C)         131487 non-null  float64
 4   기온 QC플래그       95270 non-null   float64
 5   강수량(mm)        13206 non-null   float64
 6   강수량 QC플래그      32270 non-null   float64
 7   풍속(m/s)        131437 non-null  float64
 8   풍속 QC플래그       93967 non-null   float64
 9   풍향(16방위)       131377 non-null  float64
 10  풍향 QC플래그       93967 non-null   float64
 11  습도(%)          131445 non-null  float64
 12  습도 QC플래그       95240 non-null   float64
 13  증기압(hPa)       129644 non-null  float64
 14  이슬점온도(°C)      129621 non-null  float64
 15  현지기압(hPa)      129578 non-null  float64
 16  현지기압 QC플래그     95253 non-null   float64
 17  해면기압(hPa)      129630 non-null  float64
 18  해면기압 QC플래그     95253 non-null   float64
 19  일조(hr)         71516 non-null   float64
 20  일조 QC플래그       110858 non-null  float64
 21  일사(MJ/m2)      71681 non-null   float64
 22  일사 QC플래그       110868 non-null  float64
 23  적설(cm)         6340 non-null    float64
 24  3시간신적설(cm)     432 non-null     float64
 25  전운량(10분위)      110777 non-null  float64
 26  중하층운량(10분위)    114269 non-null  float64
 27  운형(운형약어)       73445 non-null   object
 28  최저운고(100m )    63589 non-null   float64
 29  시정(10m)        117526 non-null  float64
 30  지면상태(지면상태코드)   12439 non-null   float64
 31  현상번호(국내식)      44820 non-null   float64
 32  지면온도(°C)       129089 non-null  float64
 33  지면온도 QC플래그     95385 non-null   float64
 34  5cm 지중온도(°C)   122110 non-null  float64
 35  10cm 지중온도(°C)  122109 non-null  float64
 36  20cm 지중온도(°C)  122095 non-null  float64
 37  30cm 지중온도(°C)  122005 non-null  float64
dtypes: float64(34), int64(1), object(3)
memory usage: 39.1+ MB

In [7]:
weather.columns

Index(['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '강수량(mm)', '강수량 QC플래그',
       '풍속(m/s)', '풍속 QC플래그', '풍향(16방위)', '풍향 QC플래그', '습도(%)', '습도 QC플래그',
       '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)', '현지기압 QC플래그', '해면기압(hPa)',
       '해면기압 QC플래그', '일조(hr)', '일조 QC플래그', '일사(MJ/m2)', '일사 QC플래그', '적설(cm)',
       '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)', '운형(운형약어)', '최저운고(100m )',
       '시정(10m)', '지면상태(지면상태코드)', '현상번호(국내식)', '지면온도(°C)', '지면온도 QC플래그',
       '5cm 지중온도(°C)', '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)'],
      dtype='object')

In [8]:
weather.drop(columns = ['지점', '지점명', '기온 QC플래그', '강수량 QC플래그', '풍속 QC플래그',
                        '풍향 QC플래그', '습도 QC플래그', '현지기압 QC플래그', '해면기압 QC플래그',
                        '일조 QC플래그', '일사 QC플래그', '3시간신적설(cm)', '지면상태(지면상태코드)',
                        '현상번호(국내식)', '지면온도 QC플래그'], inplace=True)
weather

,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),...,전운량(10분위),중하층운량(10분위),운형(운형약어),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2008-01-01 00:00,-7.0,NaN,3.5,270.0,52.0,1.8,-16.1,1008.0,1019.1,...,1.0,1.0,Sc,10.0,1500.0,NaN,NaN,NaN,NaN,NaN
1,2008-01-01 01:00,-7.3,NaN,4.9,290.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-01-01 02:00,-7.5,NaN,4.1,270.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-01-01 03:00,-7.8,NaN,3.9,270.0,52.0,1.6,-17.0,1008.7,1019.9,...,1.0,1.0,Sc,10.0,1500.0,-7.3,-4.0,-0.5,1.9,2.1
4,2008-01-01 04:00,-7.9,NaN,4.0,290.0,53.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00,-0.2,NaN,1.8,20.0,73.0,4.4,-4.4,1018.5,1029.4,...,0.0,0.0,NaN,NaN,1211.0,-0.9,-0.1,-0.5,-0.5,0.6
8756,2022-12-31 20:00,-0.8,NaN,1.4,20.0,75.0,4.3,-4.6,1018.1,1029.0,...,4.0,2.0,NaN,14.0,1171.0,-1.8,-0.1,-0.5,-0.5,0.6
8757,2022-12-31 21:00,-1.0,NaN,0.9,340.0,77.0,4.4,-4.5,1018.2,1029.2,...,7.0,7.0,Sc,13.0,1134.0,-2.8,-0.2,-0.5,-0.5,0.6
8758,2022-12-31 22:00,-0.8,NaN,0.5,290.0,78.0,4.5,-4.1,1018.3,1029.3,...,8.0,8.0,NaN,13.0,1094.0,-2.2,-0.3,-0.5,-0.5,0.6
8759,2022-12-31 23:00,-0.2,NaN,1.3,230.0,77.0,4.6,-3.7,1018.5,1029.4,...,8.0,8.0,NaN,14.0,1314.0,-2.1,-0.3,-0.5,-0.5,0.6

In [9]:
weather['강수량(mm)'].fillna(0, inplace=True)
weather['일조(hr)'].fillna(0, inplace=True)
weather['일사(MJ/m2)'].fillna(0, inplace=True)
weather['적설(cm)'].fillna(0, inplace=True)
weather

,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),...,전운량(10분위),중하층운량(10분위),운형(운형약어),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2008-01-01 00:00,-7.0,0.0,3.5,270.0,52.0,1.8,-16.1,1008.0,1019.1,...,1.0,1.0,Sc,10.0,1500.0,NaN,NaN,NaN,NaN,NaN
1,2008-01-01 01:00,-7.3,0.0,4.9,290.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-01-01 02:00,-7.5,0.0,4.1,270.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-01-01 03:00,-7.8,0.0,3.9,270.0,52.0,1.6,-17.0,1008.7,1019.9,...,1.0,1.0,Sc,10.0,1500.0,-7.3,-4.0,-0.5,1.9,2.1
4,2008-01-01 04:00,-7.9,0.0,4.0,290.0,53.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00,-0.2,0.0,1.8,20.0,73.0,4.4,-4.4,1018.5,1029.4,...,0.0,0.0,NaN,NaN,1211.0,-0.9,-0.1,-0.5,-0.5,0.6
8756,2022-12-31 20:00,-0.8,0.0,1.4,20.0,75.0,4.3,-4.6,1018.1,1029.0,...,4.0,2.0,NaN,14.0,1171.0,-1.8,-0.1,-0.5,-0.5,0.6
8757,2022-12-31 21:00,-1.0,0.0,0.9,340.0,77.0,4.4,-4.5,1018.2,1029.2,...,7.0,7.0,Sc,13.0,1134.0,-2.8,-0.2,-0.5,-0.5,0.6
8758,2022-12-31 22:00,-0.8,0.0,0.5,290.0,78.0,4.5,-4.1,1018.3,1029.3,...,8.0,8.0,NaN,13.0,1094.0,-2.2,-0.3,-0.5,-0.5,0.6
8759,2022-12-31 23:00,-0.2,0.0,1.3,230.0,77.0,4.6,-3.7,1018.5,1029.4,...,8.0,8.0,NaN,14.0,1314.0,-2.1,-0.3,-0.5,-0.5,0.6

In [10]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131496 entries, 0 to 8759
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   일시             131496 non-null  object
 1   기온(°C)         131487 non-null  float64
 2   강수량(mm)        131496 non-null  float64
 3   풍속(m/s)        131437 non-null  float64
 4   풍향(16방위)       131377 non-null  float64
 5   습도(%)          131445 non-null  float64
 6   증기압(hPa)       129644 non-null  float64
 7   이슬점온도(°C)      129621 non-null  float64
 8   현지기압(hPa)      129578 non-null  float64
 9   해면기압(hPa)      129630 non-null  float64
 10  일조(hr)         131496 non-null  float64
 11  일사(MJ/m2)      131496 non-null  float64
 12  적설(cm)         131496 non-null  float64
 13  전운량(10분위)      110777 non-null  float64
 14  중하층운량(10분위)    114269 non-null  float64
 15  운형(운형약어)       73445 non-null   object
 16  최저운고(100m )    63589 non-null   float64
 17  시정(10m)        117526 non-null  float64
 18  지면온도(°C)       129089 non-null  float64
 19  5cm 지중온도(°C)   122110 non-null  float64
 20  10cm 지중온도(°C)  122109 non-null  float64
 21  20cm 지중온도(°C)  122095 non-null  float64
 22  30cm 지중온도(°C)  122005 non-null  float64
dtypes: float64(21), object(2)
memory usage: 24.1+ MB

In [11]:
weather['일시'] = pd.to_datetime(weather['일시'])

In [12]:
weather

,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),...,전운량(10분위),중하층운량(10분위),운형(운형약어),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2008-01-01 00:00:00,-7.0,0.0,3.5,270.0,52.0,1.8,-16.1,1008.0,1019.1,...,1.0,1.0,Sc,10.0,1500.0,NaN,NaN,NaN,NaN,NaN
1,2008-01-01 01:00:00,-7.3,0.0,4.9,290.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-01-01 02:00:00,-7.5,0.0,4.1,270.0,52.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-01-01 03:00:00,-7.8,0.0,3.9,270.0,52.0,1.6,-17.0,1008.7,1019.9,...,1.0,1.0,Sc,10.0,1500.0,-7.3,-4.0,-0.5,1.9,2.1
4,2008-01-01 04:00:00,-7.9,0.0,4.0,290.0,53.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,-0.2,0.0,1.8,20.0,73.0,4.4,-4.4,1018.5,1029.4,...,0.0,0.0,NaN,NaN,1211.0,-0.9,-0.1,-0.5,-0.5,0.6
8756,2022-12-31 20:00:00,-0.8,0.0,1.4,20.0,75.0,4.3,-4.6,1018.1,1029.0,...,4.0,2.0,NaN,14.0,1171.0,-1.8,-0.1,-0.5,-0.5,0.6
8757,2022-12-31 21:00:00,-1.0,0.0,0.9,340.0,77.0,4.4,-4.5,1018.2,1029.2,...,7.0,7.0,Sc,13.0,1134.0,-2.8,-0.2,-0.5,-0.5,0.6
8758,2022-12-31 22:00:00,-0.8,0.0,0.5,290.0,78.0,4.5,-4.1,1018.3,1029.3,...,8.0,8.0,NaN,13.0,1094.0,-2.2,-0.3,-0.5,-0.5,0.6
8759,2022-12-31 23:00:00,-0.2,0.0,1.3,230.0,77.0,4.6,-3.7,1018.5,1029.4,...,8.0,8.0,NaN,14.0,1314.0,-2.1,-0.3,-0.5,-0.5,0.6

In [13]:
weather.columns

Index(['일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '풍향(16방위)', '습도(%)', '증기압(hPa)',
       '이슬점온도(°C)', '현지기압(hPa)', '해면기압(hPa)', '일조(hr)', '일사(MJ/m2)', '적설(cm)',
       '전운량(10분위)', '중하층운량(10분위)', '운형(운형약어)', '최저운고(100m )', '시정(10m)',
       '지면온도(°C)', '5cm 지중온도(°C)', '10cm 지중온도(°C)', '20cm 지중온도(°C)',
       '30cm 지중온도(°C)'],
      dtype='object')

In [14]:
weather['전운량(10분위)'].fillna(0, inplace=True)
weather['중하층운량(10분위)'].fillna(0, inplace=True)
weather['운형(운형약어)'].fillna(0, inplace=True)

In [15]:
weather

,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),...,전운량(10분위),중하층운량(10분위),운형(운형약어),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2008-01-01 00:00:00,-7.0,0.0,3.5,270.0,52.0,1.8,-16.1,1008.0,1019.1,...,1.0,1.0,Sc,10.0,1500.0,NaN,NaN,NaN,NaN,NaN
1,2008-01-01 01:00:00,-7.3,0.0,4.9,290.0,52.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-01-01 02:00:00,-7.5,0.0,4.1,270.0,52.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-01-01 03:00:00,-7.8,0.0,3.9,270.0,52.0,1.6,-17.0,1008.7,1019.9,...,1.0,1.0,Sc,10.0,1500.0,-7.3,-4.0,-0.5,1.9,2.1
4,2008-01-01 04:00:00,-7.9,0.0,4.0,290.0,53.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,-0.2,0.0,1.8,20.0,73.0,4.4,-4.4,1018.5,1029.4,...,0.0,0.0,0,NaN,1211.0,-0.9,-0.1,-0.5,-0.5,0.6
8756,2022-12-31 20:00:00,-0.8,0.0,1.4,20.0,75.0,4.3,-4.6,1018.1,1029.0,...,4.0,2.0,0,14.0,1171.0,-1.8,-0.1,-0.5,-0.5,0.6
8757,2022-12-31 21:00:00,-1.0,0.0,0.9,340.0,77.0,4.4,-4.5,1018.2,1029.2,...,7.0,7.0,Sc,13.0,1134.0,-2.8,-0.2,-0.5,-0.5,0.6
8758,2022-12-31 22:00:00,-0.8,0.0,0.5,290.0,78.0,4.5,-4.1,1018.3,1029.3,...,8.0,8.0,0,13.0,1094.0,-2.2,-0.3,-0.5,-0.5,0.6
8759,2022-12-31 23:00:00,-0.2,0.0,1.3,230.0,77.0,4.6,-3.7,1018.5,1029.4,...,8.0,8.0,0,14.0,1314.0,-2.1,-0.3,-0.5,-0.5,0.6

In [16]:
weather['풍향(16방위)'].unique()

array([270., 290., 340., 320., 250., 200.,   0.,  20.,  50.,  70., 360.,
       230.,  90., 140., 160., 180., 110.,  nan,  34.])

In [17]:
weather = pd.get_dummies(weather, columns=['풍향(16방위)', '운형(운형약어)'])
weather.columns

Index(['일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)', '증기압(hPa)', '이슬점온도(°C)',
       '현지기압(hPa)', '해면기압(hPa)', '일조(hr)',
       ...
       '운형(운형약어)_StAs', '운형(운형약어)_StAsCi', '운형(운형약어)_StCc', '운형(운형약어)_StCi',
       '운형(운형약어)_StNs', '운형(운형약어)_StNsAs', '운형(운형약어)_StSc', '운형(운형약어)_StScAs',
       '운형(운형약어)_StScCi', '운형(운형약어)_StScNs'],
      dtype='object', length=140)

In [ ]:
weather['풍향(16방위)_0.0'] = weather['풍향(16방위)_0.0'] + weather['풍향(16방위)_360.0']
weather.drop(columns=['풍향(16방위)_360.0'], inplace=True)

In [19]:
ways = [0, 20, 50, 70, 90, 110, 140, 160,
        180, 200, 230, 250, 270, 290, 320, 340]

In [20]:
for n in ways:
    weather[f'풍향(16방위)_{n}.0'] = weather[f'풍향(16방위)_{n}.0'] * weather['풍속(m/s)']

In [21]:
for n in ways:
    weather.rename(columns={f'풍향(16방위)_{n}.0':f'풍속(16방위)_{n}'}, inplace=True)

In [22]:
weather.columns[0:40]

Index(['일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)', '증기압(hPa)', '이슬점온도(°C)',
       '현지기압(hPa)', '해면기압(hPa)', '일조(hr)', '일사(MJ/m2)', '적설(cm)', '전운량(10분위)',
       '중하층운량(10분위)', '최저운고(100m )', '시정(10m)', '지면온도(°C)', '5cm 지중온도(°C)',
       '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)', '풍속(16방위)_0',
       '풍속(16방위)_20', '풍향(16방위)_34.0', '풍속(16방위)_50', '풍속(16방위)_70',
       '풍속(16방위)_90', '풍속(16방위)_110', '풍속(16방위)_140', '풍속(16방위)_160',
       '풍속(16방위)_180', '풍속(16방위)_200', '풍속(16방위)_230', '풍속(16방위)_250',
       '풍속(16방위)_270', '풍속(16방위)_290', '풍속(16방위)_320', '풍속(16방위)_340',
       '풍향(16방위)_360.0', '운형(운형약어)_0'],
      dtype='object')

In [23]:
weather.drop(columns=['풍향(16방위)_34.0'], inplace=True)

In [24]:
weather.columns[0:39]

Index(['일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)', '증기압(hPa)', '이슬점온도(°C)',
       '현지기압(hPa)', '해면기압(hPa)', '일조(hr)', '일사(MJ/m2)', '적설(cm)', '전운량(10분위)',
       '중하층운량(10분위)', '최저운고(100m )', '시정(10m)', '지면온도(°C)', '5cm 지중온도(°C)',
       '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)', '풍속(16방위)_0',
       '풍속(16방위)_20', '풍속(16방위)_50', '풍속(16방위)_70', '풍속(16방위)_90',
       '풍속(16방위)_110', '풍속(16방위)_140', '풍속(16방위)_160', '풍속(16방위)_180',
       '풍속(16방위)_200', '풍속(16방위)_230', '풍속(16방위)_250', '풍속(16방위)_270',
       '풍속(16방위)_290', '풍속(16방위)_320', '풍속(16방위)_340', '풍향(16방위)_360.0',
       '운형(운형약어)_0'],
      dtype='object')

In [25]:
# weather.to_csv("C:/workspace/data/기상정보/weather_preprocessed.csv", index=False)