In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname = "C:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family = font_name)

In [2]:
df = pd.read_csv("C:/workspace/data/기상정보/weather_preprocessed.csv")

In [3]:
df

,일시,기온(°C),강수량(mm),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),일조(hr),일사(MJ/m2),...,풍속(16방위)_160,풍속(16방위)_180,풍속(16방위)_200,풍속(16방위)_230,풍속(16방위)_250,풍속(16방위)_270,풍속(16방위)_290,풍속(16방위)_320,풍속(16방위)_340,풍향(16방위)_360.0
0,2008-01-01 00:00:00,-7.0,0.0,52.0,1.8,-16.1,1008.0,1019.1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0
1,2008-01-01 01:00:00,-7.3,0.0,52.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.9,0.0,0.0,0
2,2008-01-01 02:00:00,-7.5,0.0,52.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.1,0.0,0.0,0.0,0
3,2008-01-01 03:00:00,-7.8,0.0,52.0,1.6,-17.0,1008.7,1019.9,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.9,0.0,0.0,0.0,0
4,2008-01-01 04:00:00,-7.9,0.0,53.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131491,2022-12-31 19:00:00,-0.2,0.0,73.0,4.4,-4.4,1018.5,1029.4,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
131492,2022-12-31 20:00:00,-0.8,0.0,75.0,4.3,-4.6,1018.1,1029.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
131493,2022-12-31 21:00:00,-1.0,0.0,77.0,4.4,-4.5,1018.2,1029.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0
131494,2022-12-31 22:00:00,-0.8,0.0,78.0,4.5,-4.1,1018.3,1029.3,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0
131495,2022-12-31 23:00:00,-0.2,0.0,77.0,4.6,-3.7,1018.5,1029.4,0.0,0.0,...,0.0,0.0,0.0,1.3,0.0,0.0,0.0,0.0,0.0,0

In [5]:
df['일시'] = pd.to_datetime(df['일시'])
df['날짜'] = df['일시'].dt.date

In [6]:
df

,일시,기온(°C),강수량(mm),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),일조(hr),일사(MJ/m2),...,풍속(16방위)_180,풍속(16방위)_200,풍속(16방위)_230,풍속(16방위)_250,풍속(16방위)_270,풍속(16방위)_290,풍속(16방위)_320,풍속(16방위)_340,풍향(16방위)_360.0,날짜
0,2008-01-01 00:00:00,-7.0,0.0,52.0,1.8,-16.1,1008.0,1019.1,0.0,0.0,...,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0,2008-01-01
1,2008-01-01 01:00:00,-7.3,0.0,52.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.9,0.0,0.0,0,2008-01-01
2,2008-01-01 02:00:00,-7.5,0.0,52.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,4.1,0.0,0.0,0.0,0,2008-01-01
3,2008-01-01 03:00:00,-7.8,0.0,52.0,1.6,-17.0,1008.7,1019.9,0.0,0.0,...,0.0,0.0,0.0,0.0,3.9,0.0,0.0,0.0,0,2008-01-01
4,2008-01-01 04:00:00,-7.9,0.0,53.0,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0,2008-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131491,2022-12-31 19:00:00,-0.2,0.0,73.0,4.4,-4.4,1018.5,1029.4,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2022-12-31
131492,2022-12-31 20:00:00,-0.8,0.0,75.0,4.3,-4.6,1018.1,1029.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2022-12-31
131493,2022-12-31 21:00:00,-1.0,0.0,77.0,4.4,-4.5,1018.2,1029.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0,2022-12-31
131494,2022-12-31 22:00:00,-0.8,0.0,78.0,4.5,-4.1,1018.3,1029.3,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,2022-12-31
131495,2022-12-31 23:00:00,-0.2,0.0,77.0,4.6,-3.7,1018.5,1029.4,0.0,0.0,...,0.0,0.0,1.3,0.0,0.0,0.0,0.0,0.0,0,2022-12-31

In [8]:
df.columns

Index(['일시', '기온(°C)', '강수량(mm)', '습도(%)', '증기압(hPa)', '이슬점온도(°C)',
       '현지기압(hPa)', '해면기압(hPa)', '일조(hr)', '일사(MJ/m2)', '적설(cm)', '전운량(10분위)',
       '중하층운량(10분위)', '최저운고(100m )', '시정(10m)', '지면온도(°C)', '5cm 지중온도(°C)',
       '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)', '풍속(16방위)_0',
       '풍속(16방위)_20', '풍속(16방위)_50', '풍속(16방위)_70', '풍속(16방위)_90',
       '풍속(16방위)_110', '풍속(16방위)_140', '풍속(16방위)_160', '풍속(16방위)_180',
       '풍속(16방위)_200', '풍속(16방위)_230', '풍속(16방위)_250', '풍속(16방위)_270',
       '풍속(16방위)_290', '풍속(16방위)_320', '풍속(16방위)_340', '풍향(16방위)_360.0', '날짜'],
      dtype='object')

In [9]:
df_daily = df.groupby('날짜').mean()
df_daily['강수량(mm)'] = df_daily['강수량(mm)'] * 24
df_daily['적설(cm)'] = df_daily['적설(cm)'] * 24

In [10]:
df_daily

,기온(°C),강수량(mm),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),일조(hr),일사(MJ/m2),적설(cm),...,풍속(16방위)_160,풍속(16방위)_180,풍속(16방위)_200,풍속(16방위)_230,풍속(16방위)_250,풍속(16방위)_270,풍속(16방위)_290,풍속(16방위)_320,풍속(16방위)_340,풍향(16방위)_360.0
날짜,,,,,,,,,,,,,,,,,,,,,
2008-01-01,-6.337500,0.0,47.541667,1.700000,-16.612500,1009.900000,1021.037500,0.362500,0.385417,0.0,...,0.000000,0.0000,0.000000,0.000000,0.000000,1.075000,2.420833,0.079167,0.191667,0.000000
2008-01-02,-3.720833,0.0,49.708333,2.175000,-13.650000,1014.337500,1025.425000,0.370833,0.394167,0.0,...,0.000000,0.0000,0.050000,0.000000,0.700000,0.441667,0.783333,0.233333,0.000000,0.000000
2008-01-03,0.866667,0.0,51.500000,3.250000,-8.425000,1013.112500,1024.012500,0.229167,0.273750,0.0,...,0.000000,0.0000,0.000000,0.000000,0.254167,0.908333,0.229167,0.000000,0.104167,0.000000
2008-01-04,-0.379167,0.0,55.583333,3.200000,-8.650000,1015.025000,1025.975000,0.250000,0.290833,0.0,...,0.000000,0.0000,0.145833,0.000000,0.100000,0.720833,0.708333,0.079167,0.033333,0.000000
2008-01-05,1.504167,0.0,60.500000,4.000000,-5.850000,1012.537500,1023.362500,0.325000,0.333750,0.0,...,0.000000,0.0000,0.000000,0.062500,0.212500,0.437500,0.437500,0.000000,0.000000,0.125000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,-2.641667,0.0,69.208333,3.441667,-7.687500,1018.008333,1029.025000,0.366667,0.427083,3.5,...,0.000000,0.0000,0.000000,0.054167,0.037500,0.041667,0.562500,0.025000,0.041667,0.041667
2022-12-28,-2.916667,0.1,58.916667,2.916667,-10.191667,1019.058333,1030.108333,0.362500,0.452500,2.9,...,0.000000,0.0000,0.000000,0.104167,0.000000,1.012500,0.766667,0.433333,0.000000,0.000000
2022-12-29,-3.295833,0.0,54.375000,2.600000,-11.454167,1021.512500,1032.620833,0.375000,0.453333,0.0,...,0.041667,0.0000,0.087500,0.000000,0.379167,0.275000,0.475000,0.058333,0.000000,0.083333
2022-12-30,-1.383333,0.0,65.708333,3.583333,-7.362500,1020.816667,1031.816667,0.329167,0.451667,0.0,...,0.000000,0.0375,0.000000,0.150000,0.325000,0.650000,0.179167,0.045833,0.054167,0.125000
2022-12-31,-1.654167,0.0,65.708333,3.600000,-7.241667,1019.700000,1030.708333,0.045833,0.173333,0.0,...,0.000000,0.0000,0.000000,0.054167,0.000000,0.045833,0.087500,0.037500,0.062500,0.041667

In [11]:
df_daily.to_csv("C:/workspace/data/기상정보/weather_daily.csv")